const fileStructureInfo = [
  { title: "Enter datapack name", fileType: "folder", showFileBelow: true, showCheckbox: false, showInfo: false, showInfoButton: false, fileLevel: 0,
    info: "TODO" },
  { title: "pack.mcmeta", fileType: "file", showFileBelow: true, showCheckbox: false, showInfo: true, showInfoButton: false, fileLevel: 1,
    info: `{ "pack": { "description": "The default data for Minecraft", "pack_format": 61 } }` },
  { title: "pack.png", fileType: "file", showFileBelow: true, showCheckbox: false, showInfo: false, showInfoButton: false, fileLevel: 1,
    info: "TODO" },
  { title: "data", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 1,
    info: "TODO" },
  { title: "namespace", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 2,
    info: "TODO" },
  { title: "function", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "structure", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "tags", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "advancement", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "banner_pattern", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "chat_type", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "damage_type", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "dimension", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "dimension_type", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "enchantment", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "enchantment_provider", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "instrument", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "item_modifier", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "jukebox_song", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "loot_table", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "painting_variant", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "predicate", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "recipe", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "trim_material", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "trim_pattern", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "wolf_variant", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "worldgen", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 3,
    info: "TODO" },
  { title: "biome", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "configured_carver", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "configured_feature", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "density_function", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "noise", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "noise_settings", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "placed_feature", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "processor_list", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "structure", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "structure_set", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "template_pool", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "world_preset", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "flat_level_generator_preset", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" },
  { title: "multi_noise_biome_source_parameter_list", fileType: "folder", showFileBelow: true, showCheckbox: true, showInfo: false, showInfoButton: true, fileLevel: 4,
    info: "TODO" }
];